
<footer>
    <div class="card text-center text-danger letraMenu">

      <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
          <li class="nav-item">
            <p class="nav-link">Desarrollador</p>
          </li>
        </ul>
      </div>

      <div class="card-body mostrar">
        <h5 class="card-title">Desarrollado por Lorena Escobar Salamanca</h5>
        <div class="redes">
          <a href="https://www.facebook.com/lorenita.escobarsalamancadl" target="_blank"><img src="./assets/icons/Face.png"
                  alt="Facebook" onclick="return Face()" ></a>
          <a href="https://www.instagram.com/lorenita_dl/" target="_blank"><img src="./assets/icons/Insta.png" alt="Instagram"
                  onclick="return Insta()"></a>
          <a href="https://www.linkedin.com/in/lorena-escobar-salamanca-461651137/" target="_blank"><img
                  src="./assets/icons/Link.png" alt="Linkedin" onclick="return Link()"></a>
      </div>
      </div>      
    </div>
  </footer>

<script src="./js/script.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>