      <li class="nav-item">
        <a class="nav-link text-danger" href="?controller=trabajos&action=create">Nuevo Trabajo</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-danger" href="?controller=login&action=salir">salir</a>
      </li>
    </ul>
    <p class="nombreUsuario">
    <?php
      if (isset($_SESSION['nombre'])){
        echo($_SESSION['nombre']);
      } else{
        echo("");
      }      
      ?>
    </p>
  </div>
</nav>